# Generated by Django 5.1.2 on 2024-11-23 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_portal", "0003_remove_post_is_approve_alter_postcomment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="albumcomment",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="album_comments",
                to="media_portal.album",
            ),
        ),
        migrations.AlterField(
            model_name="albumlike",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="album_likes",
                to="media_portal.album",
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_likes",
                to="media_portal.post",
            ),
        ),
    ]
