# Generated by Django 5.1.2 on 2024-11-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_portal', '0003_alter_postcomment_post'),
        ('media_portal', '0004_alter_albumcomment_album_alter_albumlike_album_and_more'),
    ]

    operations = [
    ]
