# Generated by Django 5.1.2 on 2024-11-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "media_portal",
            "0004_alter_albumcomment_album_alter_albumlike_album_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
