# Generated by Django 5.1.2 on 2024-11-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_portal', '0005_alter_post_blog_alter_post_content_alter_post_title'),
        ('media_portal', '0005_merge_20241123_1249'),
    ]

    operations = [
    ]
