# Generated by Django 5.1.2 on 2024-11-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_portal', '0006_merge_20241126_0756'),
        ('media_portal', '0006_postcomment_comment_on'),
    ]

    operations = [
    ]
