# Generated by Django 5.1.2 on 2025-05-02 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_portal', '0007_merge_20241126_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryphotos',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoryphotos', to='media_portal.memories'),
        ),
        migrations.AlterField(
            model_name='memorytags',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorytags', to='media_portal.memories'),
        ),
    ]
