# Generated by Django 5.1.2 on 2025-05-07 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_portal', '0004_question_is_recommended'),
        ('job_portal', '0004_alter_jobcomment_job_alter_joblike_job_post'),
        ('media_portal', '0008_alter_memoryphotos_memory_alter_memorytags_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_portal.event'),
        ),
        migrations.AddField(
            model_name='post',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal.jobpost'),
        ),
        migrations.AddField(
            model_name='post',
            name='memories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_portal.memories'),
        ),
        migrations.AlterField(
            model_name='memoryphotos',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoryphoto', to='media_portal.memories'),
        ),
    ]
