# Generated by Django 5.1.2 on 2025-05-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_portal', '0009_post_event_post_job_post_post_memories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorytags',
            name='tag',
            field=models.CharField(max_length=255),
        ),
    ]
