# Generated by Django 5.1.2 on 2025-10-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_portal', '0010_alter_memorytags_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
