# Generated by Django 5.1.2 on 2025-07-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
