# Generated by Django 5.2.8 on 2025-12-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_chapter_chaptermembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_type',
            field=models.CharField(choices=[('Regional', 'Regional'), ('Affinity', 'Affinity'), ('International', 'International')], default='Regional', max_length=50),
        ),
        migrations.AddField(
            model_name='chapter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chapter_images/'),
        ),
    ]
