# Generated by Django 5.2.8 on 2025-12-02 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_city_country_currency_active_country_currency_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.location'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_type',
            field=models.CharField(choices=[('Regional', 'Regional'), ('Interest-Based', 'Interest-Based'), ('Department', 'Department')], default='Regional', max_length=50),
        ),
    ]
