# Generated by Django 5.1.2 on 2024-11-23 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_portal", "0003_joblike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcomment",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_comments",
                to="job_portal.jobpost",
            ),
        ),
        migrations.AlterField(
            model_name="joblike",
            name="job_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_likes",
                to="job_portal.jobpost",
            ),
        ),
    ]
