# Generated by Django 5.1.2 on 2025-09-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_alter_jobcomment_job_alter_joblike_job_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='job_pictures/'),
        ),
    ]
