# Generated by Django 5.1.2 on 2025-10-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0005_jobpost_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessdirectory',
            options={'ordering': ['-id']},
        ),
    ]
