# Generated by Django 5.1.2 on 2024-11-23 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event_portal", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventcomment",
            old_name="comment_text",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="eventcomment",
            old_name="user",
            new_name="comment_by",
        ),
    ]
