# Generated by Django 5.1.2 on 2024-11-26 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_portal", "0002_rename_comment_text_eventcomment_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcomment",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_comments",
                to="event_portal.event",
            ),
        ),
        migrations.AlterField(
            model_name="eventlike",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_likes",
                to="event_portal.event",
            ),
        ),
    ]
