# Generated by Django 5.1.2 on 2024-11-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_portal", "0003_alter_eventcomment_event_alter_eventlike_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_recommended",
            field=models.BooleanField(default=False),
        ),
    ]
